version: '3.8'

services:
  entrytracker-app:
    # השינוי כאן: במקום למשוך מה-ECR, בונים מהקוד המקומי לצורך הבדיקות ב-CI
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db-mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=app_db
    networks:
      - frontend-net
      - backend-net
    depends_on:
      - db-mysql

  db-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app_db
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-net

networks:
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge

volumes:
  db-data: